site_name: Acumatica Framework Attribute Reference
theme:
  name: material
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    logo: logo

  # Features
  features:
    - navigation.tracking
    - search.suggest

# Plugins
plugins:
  - tags
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/acumatica
